import type { ReactNode } from "react"
import { age } from "../lib/age"

export interface AiProvenance {
  /** The pill beside the title — says a model wrote what follows. */
  badge?: ReactNode | null
  /** Rendered after the badge: a matchup, a date range, whatever names the subject. */
  headerExtra?: ReactNode
  isRefreshing?: boolean
  cached?: boolean
  generatedAt?: string | null
  model?: string | null
}

/**
 * The header every AI panel wears: the title, the AI badge, how stale the
 * answer is, and which model wrote it.
 *
 * One component rather than one per panel. The insights card and the picks card
 * are different bodies with the same provenance, and the last time these were
 * written twice one of them rendered "· 8/27/2026, 11:07:59 PM" with a stray
 * separator and no model at all.
 */
export function AiPanelHeader({
  title,
  badge = "AI",
  headerExtra,
  isRefreshing = false,
  hasContent = true,
  cached = false,
  generatedAt,
  model,
  action,
}: AiProvenance & { title: ReactNode; hasContent?: boolean; action?: ReactNode }) {
  // Built as a list and joined, so a missing part cannot leave a separator
  // stranded in front of the timestamp.
  const stamp: ReactNode[] = []
  if (cached) stamp.push("Cached")
  if (isRefreshing && hasContent) stamp.push("Updating…")
  // An age, not a locale timestamp to the second: what matters is how stale
  // the answer is. The exact time stays in the tooltip.
  if (generatedAt) stamp.push(age(generatedAt) ?? new Date(generatedAt).toLocaleDateString())

  return (
    <div className="ui-insights-head">
      <div className="ui-insights-titlerow">
        <h2 className="ui-insights-title">{title}</h2>
        {badge != null && <span className="ui-insights-badge">{badge}</span>}
        {headerExtra}
      </div>
      <div className="ui-insights-controls">
        {stamp.length > 0 && (
          <span className="ui-insights-cached" title={generatedAt ?? undefined}>
            {stamp.join(" · ")}
          </span>
        )}
        {model && (
          <span className="ui-insights-model" title={`Generated by ${model}`}>
            {model}
          </span>
        )}
        {action}
      </div>
    </div>
  )
}
