import type { ReactNode } from "react"
import { cn } from "../cn"

export interface InsightSection {
  heading?: string
  bullets: ReactNode[]
  /**
   * Rendered under the section's bullets — the entities the section talks
   * about, as links. Baseball's game insights put a row of player links there
   * and that slot is the only reason its panel could not be this component.
   */
  footer?: ReactNode
}

interface Props {
  title?: string
  loading?: boolean
  /** True while a background revalidation is in flight (stale content still visible). */
  isRefreshing?: boolean
  /** The upstream response was served from cache. */
  cached?: boolean
  /** ISO timestamp when the cached answer was generated. */
  generatedAt?: string | null
  /**
   * Which model produced this, e.g. "gpt-5-nano-2025-08-07". Shown beside the
   * cache stamp.
   *
   * AI text is not like other content: two panels can look identical and be
   * the work of different models, and when an answer is wrong the first useful
   * question is which model wrote it. Both apps' backends already return this
   * — one of them was showing it and the other was not, which is exactly the
   * kind of thing that should not be a per-app decision.
   */
  model?: string | null
  /** Optional line under the title explaining what this card covers. */
  description?: ReactNode
  /** Render each section's bullets as a numbered list with chip badges instead of a plain bulleted list. */
  numbered?: boolean
  /** Regeneration callback; omit the button entirely when absent. */
  onRegenerate?: () => void
  sections: InsightSection[]
  empty?: ReactNode
  className?: string
}

/**
 * Card for AI-generated text: titled sections of bullets, a cached chip, and
 * a regenerate control. Data fetching stays in the app — pass results in.
 */
export function InsightsCard({
  title = "AI Insights",
  loading = false,
  isRefreshing = false,
  cached = false,
  generatedAt,
  model,
  description,
  numbered = false,
  onRegenerate,
  sections,
  empty = "Nothing yet.",
  className,
}: Props) {
  const hasContent = sections.some((s) => s.bullets.length > 0)
  const showSkeleton = loading && !hasContent
  const showContent = !showSkeleton && hasContent
  const generatedLabel = generatedAt ? new Date(generatedAt).toLocaleString() : null
  let bulletNumber = 0
  return (
    <div className={cn("ui-card ui-insights", className)}>
      <div className="ui-insights-head">
        <h2 className="ui-insights-title">{title}</h2>
        <div className="ui-insights-controls">
          {cached && <span className="ui-insights-cached">Cached</span>}
          {isRefreshing && hasContent && <span className="ui-insights-cached">· Updating…</span>}
          {generatedAt && <span className="ui-insights-generated" title={generatedAt}>· {generatedLabel}</span>}
          {model && (
            <span className="ui-insights-model" title={`Generated by ${model}`}>
              {model}
            </span>
          )}
          {onRegenerate && (
            <button type="button" className="ui-insights-regen" disabled={loading || isRefreshing} onClick={onRegenerate}>
              {loading || isRefreshing ? "Generating…" : "Regenerate"}
            </button>
          )}
        </div>
      </div>

      {description && <p className="ui-insights-desc">{description}</p>}

      {showSkeleton && (
        <div className="ui-insights-body">
          <span className="ui-skeleton" style={{ width: "85%" }} />
          <span className="ui-skeleton" style={{ width: "70%" }} />
          <span className="ui-skeleton" style={{ width: "78%" }} />
        </div>
      )}

      {isRefreshing && hasContent && (
        <p className="ui-insights-note">Refreshing live data… showing last good insights.</p>
      )}

      {!showSkeleton && !hasContent && <p className="ui-insights-empty">{empty}</p>}

      {showContent &&
        sections.map(
          (s, i) =>
            s.bullets.length > 0 && (
              <section key={i} className="ui-insights-body">
                {s.heading && <h3 className="ui-insights-heading">{s.heading}</h3>}
                {numbered ? (
                  <ul className="ui-insights-numbered">
                    {s.bullets.map((b) => {
                      bulletNumber += 1
                      return (
                        <li key={bulletNumber} className="ui-insights-numbered-item">
                          <span className="ui-insights-num">{bulletNumber}</span>
                          <p className="ui-insights-item-text">{b}</p>
                        </li>
                      )
                    })}
                  </ul>
                ) : (
                  <ul className="ui-insights-bullets">
                    {s.bullets.map((b, j) => (
                      <li key={j}>{b}</li>
                    ))}
                  </ul>
                )}
                {s.footer}
              </section>
            ),
        )}
    </div>
  )
}
