import type { ReactNode } from "react"
import { cn } from "../cn"
import { AiPanelHeader, type AiProvenance } from "./AiPanelHeader"

export interface Pick {
  /** The side taken. Absent on a player prop, which carries `prop` instead. */
  pick?: string | null
  confidence?: string | null
  /** The specifics behind it — a stat, a rate, a record. */
  key_factors?: string[] | null
  reasoning?: string | null
  /** Player props only. */
  player?: string | null
  prop?: string | null
}

export interface PicksCardProps extends AiProvenance {
  title?: string
  /** Moneyline, spread, total — whatever markets this sport has. */
  markets?: Array<{ label: string; pick?: Pick | null }>
  props?: Pick[] | null
  summary?: string | null
  loading?: boolean
  error?: ReactNode
  empty?: ReactNode
  /**
   * How prose renders — the app's AutoLinkedText, so player names in the
   * reasoning link the same way they do everywhere else.
   */
  renderText?: (text: string) => ReactNode
  /** How a prop's player name renders. Defaults to renderText, then plain text. */
  renderPlayer?: (name: string) => ReactNode
  /**
   * The market lines themselves. A slot rather than a shape, because the two
   * sports' odds payloads genuinely differ — one returns a structured object
   * per book, the other a single details string. Normalising that is a backend
   * change, not something to fake here.
   */
  odds?: ReactNode
  /**
   * Render without the card shell, for use inside another card's slot — a
   * MatchupCard's `foot`, which is how a picks list shows which game it is
   * talking about. The AI header stays: the model and how stale the answer is
   * matter just as much when the card is nested.
   */
  bare?: boolean
  className?: string
}

function Confidence({ level }: { level?: string | null }) {
  if (!level) return null
  const tone = level === "high" ? "high" : level === "medium" ? "med" : "low"
  return <span className={`ui-conf ui-conf--${tone}`}>{level}</span>
}

/**
 * AI betting picks for one game.
 *
 * Its own card, not a section of the insights: a pick takes a position against
 * a market and an insight describes the game, they are generated by separate
 * calls on separate cache clocks, and the gateway may route them to different
 * models. Football had no picks at all and was handing the odds to its insights
 * call instead, which is how betting language ended up in a panel that is not a
 * betting panel.
 */
export function PicksCard({
  title = "Picks",
  markets = [],
  props: playerProps,
  summary,
  loading = false,
  error,
  empty = "No picks for this game yet.",
  renderText,
  renderPlayer,
  odds,
  bare = false,
  className,
  ...provenance
}: PicksCardProps) {
  const live = markets.filter((m) => m.pick?.pick)
  const props = (playerProps ?? []).filter((p) => p.prop || p.pick)
  const hasContent = live.length > 0 || props.length > 0 || Boolean(summary)
  const text = (t?: string | null) => (t ? (renderText ? renderText(t) : t) : null)

  return (
    <div className={cn(bare ? "ui-insights ui-picks ui-picks--bare" : "ui-card ui-insights ui-picks", className)}>
      <AiPanelHeader title={title} hasContent={hasContent} {...provenance} />

      {odds}

      {loading && !hasContent && (
        <div className="ui-insights-body">
          <span className="ui-skeleton" style={{ width: "80%" }} />
          <span className="ui-skeleton" style={{ width: "65%" }} />
        </div>
      )}

      {error != null && <p className="ui-insights-note">{error}</p>}

      {!loading && !hasContent && error == null && <p className="ui-insights-empty">{empty}</p>}

      {live.length > 0 && (
        <div className="ui-insights-grid">
          {live.map(({ label, pick }) => (
            <section key={label} className="ui-insights-box">
              <div className="ui-picks-head">
                <h3 className="ui-insights-heading">{label}</h3>
                <Confidence level={pick?.confidence} />
              </div>
              <div className="ui-picks-val">{pick!.pick}</div>
              {pick?.key_factors?.length ? (
                <ul className="ui-picks-factors">
                  {pick.key_factors.map((f, i) => (
                    <li key={i}>{text(f)}</li>
                  ))}
                </ul>
              ) : null}
              {pick?.reasoning && <p className="ui-picks-reason">{text(pick.reasoning)}</p>}
            </section>
          ))}
        </div>
      )}

      {props.length > 0 && (
        <section className="ui-insights-box ui-picks-props">
          <h3 className="ui-insights-heading">Player Props</h3>
          <div className="ui-picks-propgrid">
            {props.slice(0, 4).map((p, i) => (
              <div key={i}>
                <div className="ui-picks-head">
                  <span className="ui-picks-player">
                    {p.player ? (renderPlayer ? renderPlayer(p.player) : text(p.player) ?? p.player) : null}
                  </span>
                  <Confidence level={p.confidence} />
                </div>
                <span className="ui-picks-prop">{p.prop ?? p.pick}</span>
                {p.reasoning && <p className="ui-picks-reason">{text(p.reasoning)}</p>}
              </div>
            ))}
          </div>
        </section>
      )}

      {summary && <p className="ui-picks-summary">{text(summary)}</p>}
    </div>
  )
}
